### ISSUE TITLE
Error during Kettle data extraction "Cannot find function setValue in object..."

### ISSUE THREAD

**Issue by agigatec** [fcorti/alfresco-audit-analysis-reporting#29]
After a year and a half working with the AAAR Solution with an Alfresco Community 4.2.c installation, some errors in the scheduled data extraction began to appear and no new data was imported to the aaar_datamart database.

Before facing the current error, I would list the previous solved (or at least I think so) errors (I think it would be helpful to know the background):

1. First we got erros (in the AAAR.log) like

2015/10/18 23:04:00 - stg_audits.0 - Error batch inserting rows into table [stg_audits].
2015/10/18 23:04:00 - stg_audits.0 - Errors encountered (first 10):
2015/10/18 23:04:00 - stg_audits.0 - Data truncation: Data too long for column 'values' at row 1

that we solved increasing the VARCHAR size for the column 'values'

2. Then a new error appeared

2015/10/17 23:04:15 - Modified Java Script Value.0 - ERROR (version 5.0.1-stable, build 1 from 2013-11-15_16-08-58 by buildguy) : UnexpectedError: 
2015/10/17 23:04:15 - Modified Java Script Value.0 - ERROR (version 5.0.1-stable, build 1 from 2013-11-15_16-08-58 by buildguy) : java.lang.OutOfMemoryError: Java heap space

that we solved changing the JVM memory params for Pentaho (we changed de memory params in the pentaho windows service). We didn't that changes in the spoon.bat file (is it necessary?).

3. Current error
And now the current error is

2015/10/19 23:05:01 - Modified Java Script Value.0 - Javascript error: 
2015/10/19 23:05:01 - Modified Java Script Value.0 - TypeError: Cannot find function setValue in object ADMIN. (script#24)

what I could find out about this error is that has to do with the 'compatibility mode' configuration but I don't know how to fix it or wy are I getting this error now (I've never changed this parameter).

To give you more info I must say that the AAAR installation and Alfresco are in the same server and share the same MySQL Instance who also reside in the same server.

I will appreciate your help!

**Comment by fcorti** [comment]
Hi,

Nice to hear it... I would like to have more feedback from your use case (what would you request more from AAAR?).
Please write me about this at fcorti at gmail dot com (thank you in advance).

First of all, which AAAR version are you using?

Issue 1.
I have experienced it in the past and it's due to the audit trail of a single action.
Your solution is correct.

Issue 2.
The first problem and this one are related.
Yes, you should change spoon.bat in:
set PENTAHO_DI_JAVA_OPTIONS="-Xmx512m" "-XX:MaxPermSize=256m"

Issue 3.
Don't worry, you can change the compatibility mode settings.

Let me know how it goes.

Cheers,

-F
